import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import About from "@/components/About";
import Projects from "@/components/Projects";

const sections = [
  { name: "About", component: <About /> },
  { name: "Projects", component: <Projects /> },
  // Add more sections as needed
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [activeSection, setActiveSection] = useState(0);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          <nav className="bg-black w-64 flex flex-col items-center justify-center space-y-4 text-green-500">
            {sections.map((section, index) => (
              <button
                key={index}
                onClick={() => setActiveSection(index)}
                className={`w-full py-2 text-left hover:bg-green-500 ${
                  activeSection === index ? 'bg-green-500' : ''
                }`}
              >
                {section.name}
              </button>
            ))}
          </nav>
          <main className="flex-1 p-4">
            {sections[activeSection].component}
          </main>
        </div>
      </body>
    </html>
  );
}
